version: '3.9'
services:
  # backend da aplicação
  backend:
    build:
      context: ./TodoAPI
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-db:5432/todo-db
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - postgres-db
    networks:
      - backend-network
  
  # banco de dados postgres para o backend
  postgres-db:
    image: postgres:16.2
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-db
      POSTGRES_HOST_AUTH_METHOD: 'md5'
    ports:
      - 5450:5432
    expose:
      - 5432
    networks:
      - backend-network

# networks para comunicação entre os containers
networks:
  backend-network:
    driver: bridge